// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://walsennhgpqlrcnnuzbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhbHNlbm5oZ3BxbHJjbm51emJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2NDU4MDMsImV4cCI6MjA1MjIyMTgwM30.t--ztO8SlcR9du-zCLfpjyL8sQBCQEt6GtUyq3dY6RE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);